### ISSUE TITLE
rig_tracks function causing destruction of the track data following a "short" track

### ISSUE THREAD

**Issue by elgonzo** [OpenCBM/nibtools#2]
The [rig_tracks function](https://github.com/OpenCBM/nibtools/blob/2fbb49f729b32eec3c571260ceeca317180a6dd1/fileio.c#L1312) checks for tracks being shorter than the respective track capacity, and then attempts to fill up the short track with 0x55 bytes up to the track's capacity.

However, there is a mistake in the size/count argument for the memset invocation:
```C
if(track_length[track] < capacity[track_density[track]&3])
{
	memset(track_buffer + (track*NIB_TRACK_LENGTH) + track_length[track], 0x55, capacity[track_density[track]&3]);
	//printf("Padded %d bytes\n", capacity[track_density[track]&3]-track_length[track]);
	track_length[track] = capacity[track_density[track]&3];
}
```
The size/count argument should be `capacity[track_density[track]&3] - track_length[track]` instead of just `capacity[track_density[track]&3]`. The commented out _printf_ statement got it right... ;-)

**Comment by rittwage-zz** [comment]
Fixed upstream. Thank you.
