### ISSUE TITLE
nibconv does not support half-tracks when output is a NIB file

### ISSUE THREAD

**Issue by elgonzo** [OpenCBM/nibtools#4]
When converting a G64 to NIB format with _nibconv_, half-tracks in the G64 file are read, but they are ignored when writing the data out to a NIB file.
Curiously, i found this in nibconv.c:
https://github.com/OpenCBM/nibtools/blob/2fbb49f729b32eec3c571260ceeca317180a6dd1/nibconv.c#L187-L199

Since the value of _skip_halftracks_ will always be 0 (there is no _skip_halftracks_ assignment in the entire source code for nibconv aside from the initial zero value assignment in the _main_ method) and neither _rig_tracks_ nor _write_nib_ altering _track_inc_, nibconv will **never** write half-tracks when the output file format is NIB/NBZ.

The source comment says that's intentional, but i honestly can't understand what the reasoning behind this is. Whether half-tracks should be skipped should depend either on the input file being a D64, or being a G64 file with all file offsets for half-tracks being 0x0000, or more fundamentally (and logically more sound, imo) should depend on all half-tracks having a length of 0 in the _track_length_ array, i believe.

I would have made a pull request, but that source comment makes me hesitate, as i can't shake the feeling that this comment might be an indication of an ongoing larger code overhaul that has not been committed to GitHub yet...

**Comment by spiro-trikaliotis** [comment]
Again, please contact Pete directly. He will not read this here.

**Comment by rittwage-zz** [comment]
This is because a 1541 cannot write a halftrack without destroying the immediate full tracks on either side. I could add logic to allow you to do this so long as there was no data written on these other tracks, but it would also require logic to erase the whole area first. For example, this is done with the fat track exception code.

**Comment by elgonzo** [comment]
@rittwage

Ah, thanks for the explanation, that makes sense then, i guess. However, i think it would be a good idea to alert the user when half-tracks present in the source are being ignored during conversion. Currently nibconv remains silent about this, leaving it as surprise to be discovered by the user.

(Personally, i would go as far as rejecting G64's with half-tracks while outputting some diagnostic/error message by default, and leaving it to the user to enforce either keeping or discarding of half-tracks with a commandline option or such, although this is just my subjective view and there are pros as well as cons to that view.)

**Comment by rittwage-zz** [comment]
It's a legitimate request. I will take a look at it next time I mess with the code.  I misread your original comment anyway and gave a nonsensical answer, so I need to go back and review it.  Technically, the ability to make a NIB/NBZ file from any other format was never intended - it was only made to read from disk to that format. It was added later to allow compression (NIB to NBZ)...

**Comment by rittwage-zz** [comment]
I believe the reason this code exists was to strip out halftracks where they were not needed at some point. I believe someone sent me 100's of images where they read all halftracks needlessly, so I converted them to NBZ and stripped out those tracks. I will comment out this code because I believe (at this time) it was the only reason.  Thanks!
