### ISSUE TITLE
How to compile on linux?

### ISSUE THREAD

**Issue by Zibri** [OpenCBM/nibtools#6]
I wish to compile nibconv on linux...
Any idea how?

**Comment by spiro-trikaliotis** [comment]
Sorry for the late answer, I am busy and I don't have time for my hobbies at the moment.

The easiest way to do it: Check out opencbm into a folder (for example, opencbm.git/), then put the nibtools sources into opencbm.git/opencbm/nibtools.

If you compile opencbm, it will recognize that nibtools is at the right place, and compile it alongside with opencbm itself.

**Comment by Zibri** [comment]
turns out I was doing make -f LINUX/Makefile  instead of **make -f GNU/Makefile linux**

**Comment by spiro-trikaliotis** [comment]
The LINUX/ files are for compilation as part of OpenCBM.
For stand-alone compilation, GNU/ is needed.

As this here is not an official nibtools repository but a clone for integration with OpenCBM, I naturally assume you want to cmpile it with OpenCBM.
