### ISSUE TITLE
ERROR in NIBCONV

### ISSUE THREAD

**Issue by 0wwafa** [OpenCBM/nibtools#8]
If you convert a d64 into G64 and set the speed to 300 RPM, you get a 296.4 RPM disk!

![image](https://github.com/user-attachments/assets/133c7164-d17c-433f-a6ed-e9647aa9580d)

Track 1-17 length should be 200000 / 26 = 7692 = $1E0C bytes.
On real drives the speed is almost 300 and usually creates tracks of 1E04 bytes (1541 II and 1571 have fixed speeds).

1DB2 (see picture) is 7602 (maybe a typo?) and that means 7602 * 26 = 197652; 200000/197652  * 300 = 303.56 RPM!

**Comment by spiro-trikaliotis** [comment]
Hello @0wwafa ,

please note that nibtools is not actively developed here. This is only a GIT mirror of Pete Rittwage's  SVN (cf. https://c64preservation.com/dp.php?pg=nibtools). You should contact him for any bugs, hints and whatever.

**Comment by 0wwafa** [comment]
I know.. but I also know that Pete has almost abandoned it...

**Comment by spiro-trikaliotis** [comment]
I have cloned this issue here: https://github.com/rittwage/nibtools/issues/1

I am closing it here, as I cannot do anything about it here.

**Comment by rittwage** [comment]
This is fixed on master.
